---
platform: linux

image_resource:
 type: docker-image
 source: {repository: java, tag: openjdk-8}
inputs:
 - name: pipeline-demo

outputs:
 - name: build-output
run:
 path: "pipeline-demo/ci/build.sh"